language: generic
services:
  - docker
jobs:
  include:
    - stage: build-and-test
      name: Build and Test
      before_script:
        - touch ./backend/.env.dev
        - echo SECRET_KEY=$SECRET_KEY >> ./backend/.env.dev
        - echo DEBUG=$DEBUG >> ./backend/.env.dev

      script:
        - docker-compose -f docker-compose.dev.yml run backend sh -c "coverage run manage.py test && coverage report"

      after_success:
        - docker-compose -f docker-compose.dev.yml run backend sh -c "coverage run manage.py test && TRAVIS_JOB_ID=$TRAVIS_JOB_ID TRAVIS_BRANCH=$TRAVIS_BRANCH COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls"