language: generic
services:
  - docker
jobs:
  include:
    - stage: build-and-test
      name: Build and Test
      before_script:
        - touch ./backend/.env
        - echo SECRET_KEY=$SECRET_KEY >> ./backend/.env
        - echo DEBUG=$DEBUG >> ./backend/.env
        - echo ENV=$ENV >> ./backend/.env
        - echo LOGS_ROOT=$LOGS >> ./backend/.env
        - echo REFRESH_TOKEN_SECRET_KEY=$REFRESH_SECRET >> ./backend/.env

      script:
        ./build-and-run.sh