language: generic
services:
  - docker
jobs:
  include:
    - stage: build-and-test
      name: Build and Test
      before_script:
        - touch ./backend/.env.dev
        - echo SECRET_KEY=$SECRET_KEY >> ./backend/.env.dev
        - echo DEBUG=$DEBUG >> ./backend/.env.dev

      script:
        ./build-and-run.sh