version: '3'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    backend: &backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
          - static_volume:/code/static
        ports:
            - 8000:8000
        env_file: 
            - ./backend/.env
        command: gunicorn --bind 0.0.0.0:8000 conf.wsgi
        depends_on: 
            - db

    scrapyd:
        <<: *backend
        ports:
            - 6800:6800
        tty: true
        stdin_open: true
        command: bash -c "cd scrapers && scrapyd --pidfile="

    redis: 
        image: redis:latest
    
    celeryworker:
        <<: *backend
        ports: []
        command: celery -A cars worker -l INFO

    celerybeat:
        <<: *backend
        ports: []
        command: celery -A cars beat -l INFO --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler

        
            
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes: 
            - static_volume:/usr/share/nginx/static
        ports:
            - 80:80
        depends_on:
            - backend



volumes:
  static_volume:
            