version: '3'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
          - static_volume:/code/static
        ports:
            - 8000:8000
            - 6800:6800
        env_file: 
            - ./backend/.env
        depends_on: 
            - db
            
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes: 
            - static_volume:/usr/share/nginx/static
        ports:
            - 80:80
        depends_on:
            - backend



volumes:
  static_volume:
            