version: '3'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend:/code
            - ./backend/logs/web:/logs
        ports:
            - 8000:8000
        env_file: 
            - ./backend/.env.dev
        
            