version: '3'
services:
    mongodb:
        image: 'bitnami/mongodb:latest'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword
            - MONGO_INITDB_DATABASE=django_mongodb_docker
        ports:
            - "27017:27017"

    backend: &backend
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend:/code
            - ./backend/logs/web:/logs
            - static_vol:/code/static
        ports:
            - 8000:8000
        env_file: 
            - ./backend/.env.dev
        command: python manage.py runserver 0.0.0.0:8000
        depends_on: 
            - mongodb
            - redis

    scrapyd:
        <<: *backend
        ports:
            - 6800:6800
        tty: true
        stdin_open: true
        command: bash -c "cd scrapers && scrapyd --pidfile="

    redis:
        restart: always
        image: redis:latest
        expose:
            - "6379"
    
    celeryworker:
        <<: *backend
        ports: []
        command: celery -A cars worker -l INFO

    celerybeat:
        <<: *backend
        ports: []
        command: celery -A cars beat -l INFO --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports:
            - 4200:4200
        volumes: 
            - /opt/app/node_modules
            - ./frontend:/opt/app

    
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - 80:80
        volumes:
            - static_vol:/var/www/static/
        depends_on: 
            - frontend
            - backend
        restart: on-failure
            
volumes:
    static_vol:
    mongo_db:
