# Generated by Django 3.1.2 on 2020-10-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerId', models.IntegerField(unique=True)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('production_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('primary_damage', models.CharField(max_length=50)),
                ('secondary_damage', models.CharField(max_length=50)),
                ('estimated_retail_value', models.IntegerField()),
                ('vin', models.CharField(max_length=17)),
                ('drive', models.CharField(max_length=30)),
                ('body_style', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('fuel', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=70)),
                ('sale_date', models.DateTimeField()),
                ('sale_type', models.CharField(max_length=20)),
                ('sold', models.BooleanField()),
                ('image', models.URLField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
