# Generated by Django 3.1.2 on 2020-10-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='sale_type',
        ),
    ]
