# Generated by Django 3.1.2 on 2020-10-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20201027_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
