# Generated by Django 3.1.2 on 2020-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201027_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='body_style',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='drive',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='engine',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='estimated_retail_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='fuel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='primary_damage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sale_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='secondary_damage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='transmission',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='vehicle_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='vin',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
