# Generated by Django 3.1.2 on 2020-10-27 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201027_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), null=True, size=None),
        ),
    ]
