# Generated by Django 3.1.2 on 2020-11-13 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_offer_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='auction_site',
            field=models.CharField(default='copart', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
