# Generated by Django 3.1.3 on 2020-11-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20201113_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='iaaiId',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
