# Generated by Django 3.1.3 on 2020-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20201123_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='thumb_image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
