# Generated by Django 3.1.3 on 2020-12-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20201203_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('offerId', 'auction_site')},
        ),
    ]
