# Generated by Django 3.1.3 on 2020-12-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20201204_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['model'], name='cars_offer_model_c7f9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['brand'], name='cars_offer_brand_760e44_idx'),
        ),
    ]
