# Generated by Django 3.1.4 on 2021-01-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20201222_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sale_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
